class_name ContractError
## 统一错误码集合（契约 7.6，M0 候选）。UI 用本地化文案映射这些码；
## 不把异常堆栈、用户路径或凭据显示成普通错误提示。

const NOT_AUTHENTICATED := "NOT_AUTHENTICATED"
const NOT_ALLOWED := "NOT_ALLOWED"
const WORLD_MISMATCH := "WORLD_MISMATCH"
const VERSION_MISMATCH := "VERSION_MISMATCH"
const STALE_EPOCH := "STALE_EPOCH"
const STALE_STATE := "STALE_STATE"
const INVALID_ARGUMENT := "INVALID_ARGUMENT"
const OUT_OF_RANGE := "OUT_OF_RANGE"
const INVENTORY_FULL := "INVENTORY_FULL"
const INSUFFICIENT_ITEMS := "INSUFFICIENT_ITEMS"
const INSUFFICIENT_FUNDS := "INSUFFICIENT_FUNDS"
const TARGET_CHANGED := "TARGET_CHANGED"
const RATE_LIMITED := "RATE_LIMITED"
const SEQUENCE_GAP := "SEQUENCE_GAP"
const RECEIPT_EXPIRED := "RECEIPT_EXPIRED"
const SYNC_REQUIRED := "SYNC_REQUIRED"
const MEMBER_LIMIT := "MEMBER_LIMIT"
const ONLINE_LIMIT := "ONLINE_LIMIT"
const DUPLICATE_SESSION := "DUPLICATE_SESSION"
const SAVE_FAILED := "SAVE_FAILED"
const SAVE_UNAVAILABLE := "SAVE_UNAVAILABLE"
const SERVER_CLOSING := "SERVER_CLOSING"


static func all_codes() -> PackedStringArray:
	return [
		NOT_AUTHENTICATED, NOT_ALLOWED, WORLD_MISMATCH, VERSION_MISMATCH,
		STALE_EPOCH, STALE_STATE, INVALID_ARGUMENT, OUT_OF_RANGE,
		INVENTORY_FULL, INSUFFICIENT_ITEMS, INSUFFICIENT_FUNDS, TARGET_CHANGED,
		RATE_LIMITED, SEQUENCE_GAP, RECEIPT_EXPIRED, SYNC_REQUIRED,
		MEMBER_LIMIT, ONLINE_LIMIT, DUPLICATE_SESSION,
		SAVE_FAILED, SAVE_UNAVAILABLE, SERVER_CLOSING,
	]


## 回执结构：accepted=false 表示未受理（不消耗业务序号）；
## accepted=true 表示已受理，无论业务成败都占用序号并缓存回执。
static func make_receipt(client_sequence: int, accepted: bool, error_code: String = "") -> Dictionary:
	return {
		"client_sequence": client_sequence,
		"accepted": accepted,
		"error_code": error_code,
	}
